Merged PR 6077: [IDP-1381] Provide guidance when a .NET service fails to build due to an CS2012 error
Context:

<blockquote>
We discussed that at the refinement and we decided to only print an actionnable error message because:

- .NET Aspire will offer the ability to restart services from the dashboard in version 8.1 based on the GitHub issue milestone and what Damian Edwards said on Reddit (https://www.reddit.com/r/dotnet/comments/1cxbrfe/comment/l537mkl/)
- We can't restart a service in Aspire in the meantime
- We could restart Aspire completely but this could be more annoying than anything else (plus it would require quite a lot of refactoring)

That's why we went with a cheaper option for devs to at least know what they have to do next - until Aspire 8.1 comes out.
</blockquote>

We now detect `CS2012` errors when building .NET projects by watching logs reported by Aspire. This might be a race condition where two projects referencing the same class library are built at the same time. The workaround is to restart Leap, so we print this instruction to the user.

This is how it looks when it happens:

![image.png](https://dev.azure.com/gsoft/46c89666-c1f6-4351-a213-a0a678ed8fe7/_apis/git/repositories/92e69d95-09ff-48b8-8197-a9831c6bf49b/pullRequests/6077/attachments/image.png)

We detect the text `error CS2012` from the build output and print something in our console.

> I tried to display this message in the resource logs itself (in the dashboard) but it didn't work.

```
The build failed. Fix the build errors and run again.
CSC : error CS2012: Cannot open 'C:\Users\tristan.g-hane\src\workleap-platform\organization\common\src\Workleap.Organization.Infrastructure\obj\Debug\net8.0\Workleap.Organization.Infrastructure.dll' for writing -- 'The process cannot access the file 'C:\Users\tristan.g-hane\src\workleap-platform\organization\common\src\Workleap.Organization.Infrastructure\obj\Debug\net8.0\Workleap.Organization.Infrastructure.dll' because it is being used by another process.' [C:\Users\tristan.g-hane\src\workleap-platform\organization\common\src\Workleap.Organization.Infrastructure\Workleap.Organization.Infrastructure.csproj]
```